version: '2'

services:
  codeteca:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    environment:
      - JEKYLL_ENV=production
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
